# PyTorch Tensor Functions

PyTorch provides great in-built function that help us a lot in data science. 5 of the interesting functions are provided below with their description.

- **as_tensor** - It is a function to create tensor from the given data type. It can be used as an alternative to from_numpy to create ndarray from numpy to pytorch tensor
- **as_strided** - PyToach tensor function that generates a view of the tensor. We can select the part of the tensor which we like to create view as parameters to this functions.
- **arange** - Output of the function is a tensor having values in range `[a, b)`
- **eye** - An easy method to generate identity matrix(tensor) using torch
- **where** - Change the contents of the tensor based on a condition

Before we begin, let's install and import PyTorch

In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [1]:
# Import torch and other required modules
import torch

In [2]:
import numpy as np

## Function 1 - as_tensor

Convert the data into a torch.Tensor. If the data is already a Tensor with the same dtype and device, no copy will be performed, otherwise a new Tensor will be returned with computational graph retained if data Tensor has requires_grad=True. Similarly, if the data is an ndarray of the corresponding dtype and the device is the cpu, no copy will be performed.

In [15]:
# Example 1 - working
a = np.array([1, 2, 3])
t = torch.as_tensor(a)
print("t = ", t, "\nType = ", t.dtype)

t =  tensor([1, 2, 3]) 
Type =  torch.int64


Above example shows how as_tensor works similar to from_numpy function. 

In [16]:
# Example 2 - working
a = np.array([1.5, 2.6, 3.0])
t = torch.as_tensor(a, dtype=torch.int32)
print("t = ", t, "\nType = ", t.dtype)

t =  tensor([1, 2, 3], dtype=torch.int32) 
Type =  torch.int32


We can pass some arguments to the function like **dtype** and **device**. We can just store the floating point numpy array as int32 if we pass value to the dtype parameter. If we don't specify the value will be in float64

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
a = [1.5, "a", 3.0]
t = torch.as_tensor(a, dtype=torch.int32)
print("t = ", t, "\nType = ", t.dtype)

TypeError: an integer is required (got type str)

As we know that we can also pass list to the as_tensor function. Python supports hetrogenous list values. But if we use that in as_tensor function it produces Type Error Exception

We can use the above function when we have to convert numeric value to pytorch tensor object.

## Function 2 - as_strided

Create a view of an existing torch.Tensor input with specified size, stride and storage_offset.
Parameters to function
- input (Tensor) – the input tensor.
- size (tuple or ints) – the shape of the output tensor
- stride (tuple or ints) – the stride of the output tensor
- storage_offset (int, optional) – the offset in the underlying storage of the output tensor

In [21]:
# Example 1 - working
x = torch.randn(3, 3)
print(x)
t = torch.as_strided(x, (2, 2), (1, 2))
print(t)

tensor([[ 1.1494,  0.7044,  1.0118],
        [ 0.0284,  1.2726, -2.1926],
        [-0.2235,  0.9737, -0.9755]])
tensor([[1.1494, 1.0118],
        [0.7044, 0.0284]])


We can see that we have created a view of the x tensor. t is a tensor having size 2x2 size. x tensor is traversed and the t tensor is filled column wise first.

In [23]:
# Example 2 - working
t = torch.as_strided(x, (2, 2), (1, 2), 1)
print(t)

tensor([[0.7044, 0.0284],
        [1.0118, 1.2726]])


We can set storage offset to make shift in view. See the above example for a offset of 1

In [35]:
# Example 3 - breaking
t = torch.as_strided(x, (2, 2), (1, 2), x.shape[0] * x.shape[1])
print(t)

RuntimeError: setStorage: sizes [2, 2], strides [1, 2], and storage offset 9 requiring a storage size of 13 are out of bounds for storage with numel 9

If we try to set the offset value more than the index we will get Runtime Error

We can use this function when ever we require a sub-matrix from the main matreix

## Function 3 - arange
Returns a 1-D tensor of size ⌈end−start/step⌉ with values from the interval `[start, end)` taken with common difference `step` beginning from `start`.

In [36]:
# Example 1 - working
torch.arange(5)

tensor([0, 1, 2, 3, 4])

This produces a list of 5 numbers

In [37]:
# Example 2 - working
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

We can also specify floting point range and step

In [39]:
# Example 3 - breaking
torch.arange(1, 2.5, -1)

RuntimeError: upper bound and larger bound inconsistent with step sign

We see that is the step became negative and upper bound is greater than lower bound this produces runtime error

We can use this function when we need a list of numbers in a range. For example for doing some kind of time series analytics

## Function 4 - eye
Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [40]:
# Example 1 - working
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

We see that the above function gave us an identity matrix

In [41]:
# Example 2 - working
torch.eye(3, 2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

We can give additional parameters to make the matrix of required dimension

In [42]:
# Example 3 - breaking
torch.eye(-3)

RuntimeError: n must be greater or equal to 0, got -3

We see that we can if we use negative or real numbers we will get runtime errors

We can use the above funcion when we need to create an identity matrix. Say for finding inverse of matrix.

## Function 5 - where
Return a tensor of elements selected from either x or y, depending on condition.

In [43]:
# Example 1 - working
x = torch.randn(3, 2)
y = torch.ones(3, 2)
print(x)
torch.where(x > 0, x, y)

tensor([[ 1.1204,  0.4182],
        [ 1.2382, -0.7304],
        [-1.9772, -0.1126]])


tensor([[1.1204, 0.4182],
        [1.2382, 1.0000],
        [1.0000, 1.0000]])

In [47]:
x = torch.randn(2, 2, dtype=torch.double)
y = torch.ones(2, 2, dtype=torch.double)
print(x)
torch.where(x > 0, x, y)

tensor([[-1.3434, -1.5558],
        [-1.1259,  0.4244]], dtype=torch.float64)


tensor([[1.0000, 1.0000],
        [1.0000, 0.4244]], dtype=torch.float64)

Dtype can be set as parameter to the where function. **Note that if we use dtype both x and y must be off same type**

In [48]:
x = torch.randn(2, 2, dtype=torch.double)
y = torch.ones(3, 2, dtype=torch.double)
print(x)
torch.where(x > 0, x, y)

tensor([[-0.2296, -0.3855],
        [-0.9732, -0.0333]], dtype=torch.float64)


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

If we set the dimension of both x and y as different we will get runtime error.

We can use `where` function to set the value of tensor based on the condition. say if we have to get the value of the matrix/tensor after passing through relu activation function

Let's save our work using Jovian before continuing.

## Conclusion

In this notebook we have seen some of the interesting function pytorch. Some of them are `as_tensor` - a useful function to create pytorch tensor object. If we are interested in doing sub-matrix operation there is a interesting function `as_stride`. One of the valuable function in data science, that gives a range of uniform values as a list - `arange`. We have seen `eye` which gives the matrices/tensors in shape of identity matrix. Last but not the least we have seen `where` function which is a necessary function when it comes to neural networks. If we handcode the NNs, we surely use relu activation function. These are some of the interesting 5 function available in PyTorch. More can details related to the function and additional function are provided in the official documentation.

## Reference Links
Provide links to your references and other interesting articles about tensors
* as_tensor - https://pytorch.org/docs/stable/generated/torch.as_tensor.html#torch.as_tensor
* as_stride - https://pytorch.org/docs/stable/generated/torch.as_strided.html#torch.as_strided
* arange - https://pytorch.org/docs/stable/generated/torch.arange.html#torch.arange
* eye - https://pytorch.org/docs/stable/generated/torch.eye.html#torch.eye
* where - https://pytorch.org/docs/stable/generated/torch.where.html#torch.where

In [18]:
!pip install jovian --upgrade --quiet

You should consider upgrading via the '/home/hp/env/bin/python3.5 -m pip install --upgrade pip' command.


In [49]:
import jovian

In [52]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dkowsikpai/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"


[jovian] Committed successfully! https://jovian.ai/dkowsikpai/01-tensor-operations


'https://jovian.ai/dkowsikpai/01-tensor-operations'

In [ ]:
jovian.submit(assignment="zerotogans-a1")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
